'use strict';

const SOURCE = Object.freeze({
  id: 'fifty_million_consulting_firm_fa3',
  title: 'The $50M Consulting Firm FA3',
  type: 'operator_playbook',
  authority: 'founder',
  version: 'FA3',
  requiresModel: false,
  requiresApi: false,
});

function card(input) {
  return {
    sourceId: SOURCE.id,
    sourceTitle: SOURCE.title,
    sourceType: SOURCE.type,
    authority: SOURCE.authority,
    version: SOURCE.version,
    ...input,
  };
}

const cards = Object.freeze([
  card({
    id: 'fiftym-phase-model',
    domains: ['leadership', 'growth', 'operations'],
    topics: ['phase_model', '0-5m', '5-50m', '50m+', 'firm_stage', 'scaling_stage'],
    appliesWhen: ['firm stage assessment', 'founder asks what changes at next stage', 'tenantSnapshot.firmStage present'],
    principle: 'Treat $0-5M, $5-50M, and $50M+ as different operating games with different leadership constraints.',
    evidenceSummary: 'The playbook frames consulting scale as phases where founder role, leadership team, market focus, and operating discipline must evolve.',
    metrics: [
      { name: 'annual_revenue_band', unit: 'currency_band' },
      { name: 'headcount_band', unit: 'people_band' },
    ],
    antiPatterns: ['Using startup habits to run a scale-up', 'Copying enterprise process before the firm has earned the complexity'],
    recommendedActions: ['Name the current phase', 'Coach the next leadership constraint', 'Connect phase to one operating habit'],
    coachingUse: 'Use when firmStage or scaling language is present.',
    promptUse: 'Inject when tenantSnapshot.firmStage.revenueBand is available or user asks about scaling stages.',
    confidence: 'high',
    sourceNotes: ['Product-safe synthesis of the phase model.'],
  }),
  card({
    id: 'fiftym-founder-bottleneck-wall-1',
    domains: ['leadership', 'growth', 'operations'],
    topics: ['founder_bottleneck', 'wall_1', 'delegation', 'team_selling', '5-50m'],
    appliesWhen: ['founder owns sales delivery and decisions', 'team cannot scale decisions', 'firm in early scale-up'],
    principle: 'Wall #1 appears when founder judgment is still the operating system; the next move is delegation with discipline, not founder heroics.',
    evidenceSummary: 'Growing past early scale requires moving client, sales, delivery, and management decisions into a capable leadership system.',
    metrics: [
      { name: 'decision_concentration', unit: 'qualitative' },
      { name: 'multi_leader_ownership', unit: 'percent' },
    ],
    antiPatterns: ['Founder personally rescues every at-risk project', 'All meaningful sales relationships route through one person'],
    recommendedActions: ['Identify founder-owned decisions that need owners', 'Build leadership cadence around those decisions', 'Use team selling to reduce founder sales concentration'],
    coachingUse: 'Use for founder-dependency and leadership delegation coaching.',
    promptUse: 'Inject when userMessage includes founder, bottleneck, delegation, or team selling.',
    confidence: 'high',
    sourceNotes: ['No long excerpts; distilled operator principle.'],
  }),
  card({
    id: 'fiftym-wall-2-25-40m',
    domains: ['leadership', 'operations', 'growth'],
    topics: ['wall_2', '25-40m', 'leadership_system', 'market_focus', 'operating_system', '50m+'],
    appliesWhen: ['firm approaching 25-40M', 'complexity rising', 'leadership system strain', 'growth plateau'],
    principle: 'Wall #2 is usually an operating complexity problem: leadership system, market focus, delivery repeatability, and margin discipline must tighten together.',
    evidenceSummary: 'Firms approaching larger scale need stronger operating architecture; informal coordination no longer handles complexity.',
    metrics: [
      { name: 'annual_revenue_band', unit: 'currency_band' },
      { name: 'leadership_coverage', unit: 'qualitative' },
      { name: 'margin_consistency', unit: 'percent' },
    ],
    antiPatterns: ['Adding managers without clarifying operating cadence', 'Expanding markets while delivery method is inconsistent'],
    recommendedActions: ['Review leadership accountabilities', 'Tighten market focus', 'Standardize delivery and operating rhythms'],
    coachingUse: 'Use for larger-firm scaling issues and executive operating model coaching.',
    promptUse: 'Inject when firmStage suggests 25-40M or user asks about scaling beyond current leadership system.',
    confidence: 'high',
    sourceNotes: ['Supports future stage-aware coaching.'],
  }),
  card({
    id: 'fiftym-leadership-team',
    domains: ['leadership', 'operations', 'talent'],
    topics: ['leadership_team', 'delegation', 'accountability', 'operating_cadence', 'management_layer'],
    appliesWhen: ['leadership accountability unclear', 'founder asks how to scale', 'operating cadence lacks owners'],
    principle: 'A real leadership team owns decisions, metrics, and follow-through; it is not just a group of senior practitioners.',
    evidenceSummary: 'Scaling requires leaders who can own sales, delivery, talent, finance, and operations decisions without routing every call back to the founder.',
    metrics: [
      { name: 'decision_owner_coverage', unit: 'percent' },
      { name: 'cadence_follow_through', unit: 'qualitative' },
    ],
    antiPatterns: ['Promoting experts without decision authority', 'Holding meetings that produce no owner or next action'],
    recommendedActions: ['Assign named owners to operating metrics', 'Separate advisory input from decision rights', 'Use cadence to inspect follow-through'],
    coachingUse: 'Use when insights need leadership ownership rather than analyst-style reporting.',
    promptUse: 'Inject when user asks who should own an issue or when multiple recurring issues lack owners.',
    confidence: 'high',
    sourceNotes: ['Operator principle, not an org-design prescription.'],
  }),
  card({
    id: 'fiftym-farming-existing-clients',
    domains: ['growth', 'client_relationships', 'sales'],
    topics: ['farming_existing_clients', 'account_growth', 'client_expansion', 'qbr', 'brag_sheet', 'team_selling'],
    appliesWhen: ['growth from existing clients', 'client expansion opportunity', 'pipeline gap', 'relationship review'],
    principle: 'Existing clients are often the most efficient growth source when delivery value is made visible and converted into structured expansion conversations.',
    evidenceSummary: 'The founder/operator playbook emphasizes farming current relationships, not only hunting new logos, as firms scale beyond founder-led selling.',
    metrics: [
      { name: 'account_expansion_pipeline', unit: 'currency' },
      { name: 'repeat_revenue_ratio', unit: 'percent' },
      { name: 'relationship_coverage', unit: 'percent' },
    ],
    antiPatterns: ['Waiting for the client to ask what is next', 'Treating delivery success as separate from sales motion'],
    recommendedActions: ['Identify top accounts with recent value proof', 'Prepare expansion themes from delivery outcomes', 'Assign account owners for follow-up'],
    coachingUse: 'Use when pipeline gap can be addressed through account expansion.',
    promptUse: 'Inject when userMessage includes farming, existing clients, account growth, client expansion, or pipeline gap.',
    confidence: 'high',
    sourceNotes: ['Summarizes account farming concept without quoting source material.'],
  }),
  card({
    id: 'fiftym-gtm-hourglass',
    domains: ['growth', 'commercial_strategy'],
    topics: ['gtm_hourglass', 'market_focus', 'pipeline', 'qualification', 'positioning', 'sales_process'],
    appliesWhen: ['go-to-market shape unclear', 'pipeline quality problem', 'too many segments', 'poor qualification'],
    principle: 'A strong go-to-market hourglass narrows focus before scaling activity and expands through repeatable delivery, proof, and client growth.',
    evidenceSummary: 'The hourglass concept helps firms avoid broad unfocused selling by tightening market selection and then widening through trust and expansion.',
    metrics: [
      { name: 'qualified_pipeline_ratio', unit: 'percent' },
      { name: 'conversion_by_stage', unit: 'percent' },
      { name: 'account_expansion_pipeline', unit: 'currency' },
    ],
    antiPatterns: ['Pouring more leads into a leaky or unfocused motion', 'Treating qualification as a late-stage sales task'],
    recommendedActions: ['Clarify target segment', 'Inspect where opportunities leak', 'Turn delivery proof into expansion motion'],
    coachingUse: 'Use for strategic growth coaching beyond simple pipeline volume.',
    promptUse: 'Inject when user asks about GTM, market focus, qualification, or pipeline quality.',
    confidence: 'high',
    sourceNotes: ['Product-safe synthesis of GTM hourglass.'],
  }),
  card({
    id: 'fiftym-qbrs-and-brag-sheets',
    domains: ['growth', 'client_relationships', 'operations'],
    topics: ['qbr', 'brag_sheet', 'client_value', 'account_growth', 'proof_of_value'],
    appliesWhen: ['client expansion', 'relationship review', 'need to show delivered value', 'account planning'],
    principle: 'QBRs and brag sheets convert delivered work into visible business value and create a natural bridge to the next conversation.',
    evidenceSummary: 'Founder/operator practice emphasizes making outcomes explicit so clients see the value delivered and the firm can farm intelligently.',
    metrics: [
      { name: 'qbr_coverage', unit: 'percent' },
      { name: 'client_value_proofs', unit: 'count' },
      { name: 'expansion_actions', unit: 'count' },
    ],
    antiPatterns: ['Only talking to clients when selling or escalating', 'Letting great delivery disappear into project archives'],
    recommendedActions: ['Prepare a short value summary for key accounts', 'Schedule QBRs around outcomes and next problems', 'Attach expansion follow-ups to client proof'],
    coachingUse: 'Use for account growth and client relationship recommendations.',
    promptUse: 'Inject when userMessage includes QBR, account review, brag sheet, client value, or expansion.',
    confidence: 'high',
    sourceNotes: ['No raw playbook text included.'],
  }),
  card({
    id: 'fiftym-repeatable-delivery-methodology',
    domains: ['operations', 'delivery', 'service_execution'],
    topics: ['repeatable_delivery_methodology', 'delivery_consistency', 'project_margin', 'on_time_delivery', 'quality'],
    appliesWhen: ['project overruns repeat', 'delivery margin inconsistent', 'quality depends on heroics', 'scale delivery'],
    principle: 'Repeatable delivery methodology lets the firm scale quality and margin without relying on individual heroics.',
    evidenceSummary: 'At scale, delivery consistency becomes a growth and profitability asset because clients get predictable outcomes and teams know how work should run.',
    metrics: [
      { name: 'project_margin_consistency', unit: 'percent' },
      { name: 'project_overrun_rate', unit: 'percent' },
      { name: 'on_time_delivery', unit: 'percent' },
    ],
    antiPatterns: ['Every project invents its own delivery process', 'High performers compensate for weak methodology'],
    recommendedActions: ['Identify repeated overrun patterns', 'Standardize delivery checkpoints', 'Connect methodology gaps to project margin actions'],
    coachingUse: 'Use for repeated project margin or delivery quality issues.',
    promptUse: 'Inject when project overruns, delivery margin, or repeatability are present.',
    confidence: 'high',
    sourceNotes: ['Pairs with Projectworks Method L3 delivery margins.'],
  }),
  card({
    id: 'fiftym-operations-enable-scale',
    domains: ['operations', 'leadership', 'finance'],
    topics: ['operations_enable_scale', 'operating_system', 'cadence', 'visibility', 'margin_control', 'cash'],
    appliesWhen: ['growth creates operational strain', 'multiple issues recurring', 'leadership wants scale without chaos'],
    principle: 'Operations should enable scale by making the business visible, predictable, and decision-ready.',
    evidenceSummary: 'The operator playbook treats operations as the system that lets leaders scale without founder bottlenecks, margin surprises, and delivery chaos.',
    metrics: [
      { name: 'operating_cadence_health', unit: 'qualitative' },
      { name: 'margin_visibility', unit: 'boolean' },
      { name: 'cash_visibility', unit: 'boolean' },
    ],
    antiPatterns: ['Adding process that slows decisions', 'Letting growth outpace finance and delivery controls'],
    recommendedActions: ['Focus operations on decision speed and visibility', 'Prioritize recurring surprises first', 'Connect every report to a management action'],
    coachingUse: 'Use as executive framing for proactive assistant operating feed priorities.',
    promptUse: 'Inject when multiple operating signals need prioritization for a leader.',
    confidence: 'high',
    sourceNotes: ['Supports the product thesis without creating UI terminology.'],
  }),
  card({
    id: 'fiftym-metrics-that-matter',
    domains: ['leadership', 'finance', 'growth', 'operations'],
    topics: ['metrics_that_matter', 'margin', 'utilisation', 'utilization', 'revenue_confidence', 'book_to_bill', 'pipeline', 'profitability'],
    appliesWhen: ['CEO metrics', 'executive summary', 'prioritization', 'leadership wants what matters'],
    principle: 'The metrics that matter most for a scaling consulting firm are margin, utilisation, revenue confidence, and book-to-bill because they connect today delivery to tomorrow growth.',
    evidenceSummary: 'Founder/operator operating cadence should focus on the small set of signals that expose whether the firm is selling, staffing, delivering, and profiting predictably.',
    metrics: [
      { name: 'margin', unit: 'percent' },
      { name: 'utilisation', unit: 'percent' },
      { name: 'revenue_confidence', unit: 'qualitative' },
      { name: 'book_to_bill', unit: 'ratio' },
    ],
    antiPatterns: ['Overloading leaders with dashboard clutter', 'Choosing metrics that do not support a decision'],
    recommendedActions: ['Rank issues by commercial consequence', 'Show one priority and two supporting signals', 'Use follow-up cadence for unresolved risks'],
    coachingUse: 'Use for calm executive prioritization and what-matters-today summaries.',
    promptUse: 'Inject when user asks what matters, what to prioritize, or how the business is tracking.',
    confidence: 'high',
    sourceNotes: ['Designed to support the assistant operating partner direction.'],
  }),
  card({
    id: 'fiftym-platform-company-traits',
    domains: ['leadership', 'operations', 'growth'],
    topics: ['platform_company', '50m+', 'scalable_systems', 'leadership_depth', 'repeatability', 'market_focus'],
    appliesWhen: ['aspiration to scale beyond current firm stage', 'platform company discussion', 'leadership asks what great looks like'],
    principle: 'A platform consulting company has leadership depth, repeatable delivery, focused go-to-market, operating visibility, and disciplined economics.',
    evidenceSummary: 'The playbook points toward a company that is not dependent on one founder or a handful of heroic practitioners to sell, deliver, and manage performance.',
    metrics: [
      { name: 'leadership_depth', unit: 'qualitative' },
      { name: 'delivery_repeatability', unit: 'qualitative' },
      { name: 'margin_consistency', unit: 'percent' },
    ],
    antiPatterns: ['Mistaking size for scalability', 'Scaling headcount before the operating model is repeatable'],
    recommendedActions: ['Compare current operating habits to platform traits', 'Pick the constraint that blocks the next stage', 'Frame recommendations around scalable systems'],
    coachingUse: 'Use when the assistant needs to describe the next level without generic business advice.',
    promptUse: 'Inject when user asks about becoming scalable, platform-like, or ready for the next stage.',
    confidence: 'high',
    sourceNotes: ['Aspirational operator framing; not a claim about current tenant capability.'],
  }),
]);

module.exports = {
  source: {
    ...SOURCE,
    cards,
  },
};
