'use strict';

const SOURCE = Object.freeze({
  id: 'projectworks_method_operations_v8',
  title: 'Projectworks Method Operations V8',
  type: 'methodology',
  authority: 'projectworks',
  version: 'v8',
  requiresModel: false,
  requiresApi: false,
});

function card(input) {
  return {
    sourceId: SOURCE.id,
    sourceTitle: SOURCE.title,
    sourceType: SOURCE.type,
    authority: SOURCE.authority,
    version: SOURCE.version,
    ...input,
  };
}

const cards = Object.freeze([
  card({
    id: 'pwm-ops-how-profitable-are-you',
    domains: ['operations', 'finance', 'profitability', 'delivery'],
    topics: ['profitability', 'project_margin', 'firm_margin', 'wip', 'accounts_receivable', 'ar', 'invoice', 'cash'],
    appliesWhen: ['profitability question', 'margin issue', 'overdue invoice', 'uninvoiced wip', 'cash risk'],
    principle: 'Start operations coaching with the concrete profitability question: where is margin, cash, or delivery control leaking right now?',
    evidenceSummary: 'The operations track moves from admin discipline to visibility, delivery margin, and firm margin so the firm can see and act on profit drivers.',
    metrics: [
      { name: 'project_margin', unit: 'percent' },
      { name: 'services_margin', unit: 'percent' },
      { name: 'uninvoiced_wip', unit: 'currency' },
      { name: 'overdue_ar', unit: 'currency' },
    ],
    antiPatterns: ['Opening with generic reporting advice', 'Separating overdue AR, WIP, and margin into unrelated conversations'],
    recommendedActions: ['Name the biggest profitability leak', 'Tie the leak to a Projectworks operating level', 'Recommend one decision or follow-up action'],
    coachingUse: 'Use for finance, WIP, AR, margin, and profitability insight framing.',
    promptUse: 'Inject when a tenant fact contains overdueInvoices, uninvoicedWip, low project margin, or margin questions.',
    confidence: 'high',
    sourceNotes: ['Summarized from Projectworks operations methodology; no source document text embedded.'],
  }),
  card({
    id: 'pwm-ops-l0-switch',
    domains: ['operations', 'implementation', 'data_foundation'],
    topics: ['l0', 'switch', 'go_live', 'data_import', 'setup'],
    appliesWhen: ['tenant is new', 'data foundation missing', 'implementation or migration context'],
    principle: 'L0 is about switching on Projectworks with enough clean data and team confidence to run the business from it.',
    evidenceSummary: 'Without a trusted data foundation, later reports, insights, and actions will create noise rather than operating clarity.',
    metrics: [
      { name: 'go_live_readiness', unit: 'qualitative' },
      { name: 'core_data_completeness', unit: 'percent' },
    ],
    antiPatterns: ['Layering advanced coaching over incomplete setup', 'Treating missing foundational data as an insight rather than an implementation blocker'],
    recommendedActions: ['Confirm core project, people, client, rate, and time data is present', 'Keep advice practical until data trust improves'],
    coachingUse: 'Use when tenant context indicates setup or data completeness issues.',
    promptUse: 'Inject when operationsLevel is 0 or implementation language appears.',
    confidence: 'high',
    sourceNotes: ['Initial source card for future onboarding-aware coaching.'],
  }),
  card({
    id: 'pwm-ops-l1-lean-admin',
    domains: ['operations', 'admin', 'finance'],
    topics: ['l1', 'lean_admin', 'timesheets', 'invoice', 'billing', 'accounts_receivable', 'ar', 'cash'],
    appliesWhen: ['timesheet completion issue', 'invoice process issue', 'admin drag', 'overdue invoice', 'cash collection follow-up'],
    principle: 'L1 removes admin friction so timesheets, approvals, invoices, and billing follow-up happen reliably.',
    evidenceSummary: 'Lean admin is the first operating layer: complete timesheets, review exceptions, and keep billing motion clean before optimizing higher-level margins.',
    metrics: [
      { name: 'timesheet_completion_rate', target: '80+', unit: 'percent' },
      { name: 'invoice_generation_from_timesheets', unit: 'boolean' },
      { name: 'overdue_ar', unit: 'currency' },
    ],
    antiPatterns: ['Letting time capture failures become billing surprises', 'Waiting for month-end to find missing approvals or invoices'],
    recommendedActions: ['Nudge missing timesheets', 'Review billing exceptions weekly', 'Prepare invoice follow-up when AR ages'],
    coachingUse: 'Use for missing timesheets, invoicing basics, overdue AR, and admin discipline.',
    promptUse: 'Inject when insight.metric is missing timesheets, overdueInvoices, invoice, billing, or AR.',
    confidence: 'high',
    sourceNotes: ['AR application is product-safe extension of billing discipline.'],
  }),
  card({
    id: 'pwm-ops-l2-visibility',
    domains: ['operations', 'resourcing', 'service_execution'],
    topics: ['l2', 'visibility', 'utilisation', 'utilization', 'forward_booking', 'capacity', 'resource_planning'],
    appliesWhen: ['utilisation gap', 'forward booking below target', 'resource planning risk', 'delivery visibility issue'],
    principle: 'L2 creates forward visibility: resourcing, utilisation, and pipeline-to-capacity signals are reviewed before delivery risk arrives.',
    evidenceSummary: 'Visibility depends on booking ahead, watching utilisation, and connecting resourcing decisions to deal flow.',
    metrics: [
      { name: 'forward_booking_weeks', target: '8', unit: 'weeks' },
      { name: 'billable_utilisation', target: '68-70', unit: 'percent' },
      { name: 'weekly_resource_meeting', unit: 'boolean' },
    ],
    antiPatterns: ['Discovering capacity gaps only after projects start', 'Looking at utilisation without the next eight weeks of bookings'],
    recommendedActions: ['Show booking gaps by person', 'Connect utilisation outliers to future allocation', 'Run a weekly resource review'],
    coachingUse: 'Use for utilisation, capacity, and forward booking insights.',
    promptUse: 'Inject when operationsLevelName is Visibility or insight.metric is utilisationRate or forwardBookingWeeks.',
    confidence: 'high',
    sourceNotes: ['Matches current tenant snapshot methodContext for L2 operations.'],
  }),
  card({
    id: 'pwm-ops-l3-delivery-margins',
    domains: ['operations', 'delivery', 'finance', 'project_control'],
    topics: ['l3', 'delivery_margins', 'project_margin', 'burn_rate', 'budget_overrun', 'wip'],
    appliesWhen: ['project margin risk', 'budget overrun', 'burn rate issue', 'WIP review'],
    principle: 'L3 turns project delivery into margin control by making burn, WIP, and cost-to-complete visible before closeout.',
    evidenceSummary: 'Delivery margin maturity requires every active project to surface margin risk early enough for a PM, commercial, or scope decision.',
    metrics: [
      { name: 'project_margin', unit: 'percent' },
      { name: 'budget_burn', unit: 'percent' },
      { name: 'weekly_wip_review', unit: 'boolean' },
    ],
    antiPatterns: ['Running WIP review as status reporting only', 'Finding project loss after the team has already spent the budget'],
    recommendedActions: ['Review over-budget projects by named owner', 'Separate scope, staffing, and commercial actions', 'Make WIP review a decision forum'],
    coachingUse: 'Use for at-risk projects, margin leaks, and WIP-to-action coaching.',
    promptUse: 'Inject when insight.type is at_risk for a project, or userMessage includes project margin, burn, budget, or WIP.',
    confidence: 'high',
    sourceNotes: ['Product-safe summary of L3 operations.'],
  }),
  card({
    id: 'pwm-ops-l4-firm-margins',
    domains: ['operations', 'finance', 'leadership'],
    topics: ['l4', 'firm_margins', 'forecasting', 'services_margin', 'ebitda', 'operating_margin'],
    appliesWhen: ['firm-level profitability', 'forecast vs actual', 'executive margin review', 'financial operating cadence'],
    principle: 'L4 shifts from project-level control to firm-level margin forecasting and deliberate executive tradeoffs.',
    evidenceSummary: 'At this level, leaders need predictable revenue, margin, and capacity signals that support portfolio decisions rather than isolated project fixes.',
    metrics: [
      { name: 'firm_margin_reporting', unit: 'boolean' },
      { name: 'forecasting_enabled', unit: 'boolean' },
      { name: 'services_margin', unit: 'percent' },
    ],
    antiPatterns: ['Using project health alone as a firm-margin proxy', 'Blending forecast and actuals without a clean boundary'],
    recommendedActions: ['Run monthly firm margin review', 'Compare forecast to actual with explicit definitions', 'Link margin gaps to pricing, delivery, or overhead levers'],
    coachingUse: 'Use for director-level firm margin, forecasting, and EBITDA conversations.',
    promptUse: 'Inject when operationsLevel is 4 or userMessage includes firm margin, forecast, EBITDA, or services margin.',
    confidence: 'high',
    sourceNotes: ['Keeps forecast and actual concepts separated.'],
  }),
  card({
    id: 'pwm-ops-data-reporting-insight-action-loop',
    domains: ['operations', 'methodology', 'action_awareness'],
    topics: ['data_reporting_insight_action', 'decision_loop', 'insight_to_action', 'follow_up', 'accounts_receivable', 'ar', 'wip'],
    appliesWhen: ['insight needs follow-up', 'user asks what to do next', 'report has no action owner', 'overdue AR or WIP needs action'],
    principle: 'The method is data to reporting to insight to action; the assistant should move the user toward a decision, not stop at observation.',
    evidenceSummary: 'Projectworks Method installs disciplined decision loops so data becomes operating action through cadence, ownership, and follow-up.',
    metrics: [
      { name: 'decision_owner', unit: 'qualitative' },
      { name: 'follow_up_action', unit: 'qualitative' },
    ],
    antiPatterns: ['Showing a dashboard and calling the work done', 'Offering manual instructions when the product should prepare the action'],
    recommendedActions: ['State the decision the insight supports', 'Prepare a safe action plan when appropriate', 'Respect action capability availability before claiming execution'],
    coachingUse: 'Use to preserve proactive assistant behavior while staying truthful about unavailable writes.',
    promptUse: 'Inject when an insight should lead to confirmation, action preparation, or follow-up.',
    confidence: 'high',
    sourceNotes: ['Aligns with current action capability contract.'],
  }),
  card({
    id: 'pwm-ops-weekly-monthly-operating-cadence',
    domains: ['operations', 'leadership', 'cadence'],
    topics: ['weekly_cadence', 'monthly_cadence', 'resource_meeting', 'wip_review', 'margin_review', 'pipeline_review'],
    appliesWhen: ['recurring operating issue', 'need a decision cadence', 'leadership wants rhythm', 'multiple insights same week'],
    principle: 'Weekly cadence handles near-term resource, WIP, and delivery decisions; monthly cadence handles firm margin, forecast, and strategic performance.',
    evidenceSummary: 'Operating cadence prevents surprises by making the right facts visible at the right decision frequency.',
    metrics: [
      { name: 'weekly_resource_meeting', unit: 'boolean' },
      { name: 'weekly_wip_review', unit: 'boolean' },
      { name: 'monthly_margin_review', unit: 'boolean' },
    ],
    antiPatterns: ['Turning every metric into a meeting', 'Reviewing urgent weekly issues only in a monthly forum'],
    recommendedActions: ['Match each insight to weekly or monthly cadence', 'Keep cadence action-oriented', 'Carry unresolved risks into the next assistant follow-up'],
    coachingUse: 'Use when converting multiple insights into a calm operating rhythm.',
    promptUse: 'Inject for cadence, follow-up, resource review, WIP review, and margin review requests.',
    confidence: 'high',
    sourceNotes: ['Future cadence engine can select this card from normalized facts.'],
  }),
]);

module.exports = {
  source: {
    ...SOURCE,
    cards,
  },
};
