'use strict';

const SOURCE = Object.freeze({
  id: 'projectworks_method_growth_v8',
  title: 'Projectworks Method Growth V8',
  type: 'methodology',
  authority: 'projectworks',
  version: 'v8',
  requiresModel: false,
  requiresApi: false,
});

function card(input) {
  return {
    sourceId: SOURCE.id,
    sourceTitle: SOURCE.title,
    sourceType: SOURCE.type,
    authority: SOURCE.authority,
    version: SOURCE.version,
    ...input,
  };
}

const cards = Object.freeze([
  card({
    id: 'pwm-growth-how-fast-are-you-growing',
    domains: ['growth', 'commercial', 'leadership'],
    topics: ['growth_rate', 'pipeline', 'revenue_confidence', 'book_to_bill', 'sales_velocity'],
    appliesWhen: ['leadership asks about growth', 'pipeline gap', 'revenue confidence issue', 'commercial review'],
    principle: 'Growth coaching starts by asking whether the firm can see, win, and deliver enough right-fit work to support its ambition.',
    evidenceSummary: 'The growth track moves from winning more work to team selling, repeatable growth, and revenue efficiency.',
    metrics: [
      { name: 'pipeline_coverage', unit: 'multiple' },
      { name: 'book_to_bill', unit: 'ratio' },
      { name: 'revenue_confidence', unit: 'qualitative' },
    ],
    antiPatterns: ['Discussing growth without pipeline quality', 'Treating sales as separate from delivery capacity'],
    recommendedActions: ['Check pipeline coverage and confidence', 'Connect pipeline to resourcing', 'Name the next growth operating habit'],
    coachingUse: 'Use for commercial leadership questions and pipeline gaps.',
    promptUse: 'Inject when userMessage includes growth, pipeline, revenue confidence, or book-to-bill.',
    confidence: 'high',
    sourceNotes: ['Summarized from Projectworks Growth Method V8.'],
  }),
  card({
    id: 'pwm-growth-l0-switch',
    domains: ['growth', 'commercial_foundation', 'implementation'],
    topics: ['l0', 'switch', 'commercial_setup', 'crm_foundation', 'data_foundation'],
    appliesWhen: ['growth data missing', 'new implementation', 'commercial system not trusted'],
    principle: 'Growth L0 establishes enough commercial data structure to see opportunities, clients, stages, and ownership.',
    evidenceSummary: 'Without consistent opportunity and client data, growth coaching turns into anecdotes rather than operating intelligence.',
    metrics: [
      { name: 'opportunity_data_completeness', unit: 'percent' },
      { name: 'owner_coverage', unit: 'percent' },
    ],
    antiPatterns: ['Forecasting from incomplete opportunity data', 'Ignoring ownership gaps in early growth setup'],
    recommendedActions: ['Confirm client and opportunity fields are complete', 'Name missing owners before forecast coaching'],
    coachingUse: 'Use when growth data quality is the constraint.',
    promptUse: 'Inject when growthLevel is 0 or commercial data foundation language appears.',
    confidence: 'high',
    sourceNotes: ['Initial source card for future commercial onboarding.'],
  }),
  card({
    id: 'pwm-growth-l1-win-more-work',
    domains: ['growth', 'sales', 'commercial'],
    topics: ['l1', 'win_more_work', 'proposal_volume', 'win_rate', 'pipeline', 'icp'],
    appliesWhen: ['proposal volume issue', 'win rate issue', 'early growth discipline', 'need more work'],
    principle: 'L1 focuses on creating enough qualified selling motion to win more right-fit work.',
    evidenceSummary: 'The first growth habit is visibility into proposals, win rate, and whether opportunities fit the firm focus.',
    metrics: [
      { name: 'proposal_volume_tracked', unit: 'boolean' },
      { name: 'win_rate_tracked', unit: 'boolean' },
      { name: 'qualified_pipeline', unit: 'currency' },
    ],
    antiPatterns: ['Chasing any revenue regardless of fit', 'Letting proposal activity go unmeasured'],
    recommendedActions: ['Track proposal volume and win rate', 'Separate qualified from unqualified pipeline', 'Review ICP fit on active opportunities'],
    coachingUse: 'Use when the user asks how to win more work or fill near-term demand.',
    promptUse: 'Inject when growthLevelName is Win More Work or userMessage includes win rate, proposal, or pipeline.',
    confidence: 'high',
    sourceNotes: ['Product-safe summary of L1 growth.'],
  }),
  card({
    id: 'pwm-growth-l2-team-selling',
    domains: ['growth', 'sales', 'talent', 'leadership'],
    topics: ['l2', 'team_selling', 'pipeline_visible_to_team', 'account_expansion', 'delivery_involved_in_sales'],
    appliesWhen: ['sales depends on founder', 'pipeline not visible to delivery', 'team selling gap', 'account growth issue'],
    principle: 'L2 turns selling from founder-led effort into a team sport where delivery and client owners contribute to growth.',
    evidenceSummary: 'Team selling improves revenue confidence because more people see, shape, and progress the right opportunities.',
    metrics: [
      { name: 'pipeline_visible_to_team', unit: 'boolean' },
      { name: 'multi_person_opportunity_coverage', unit: 'percent' },
      { name: 'account_expansion_opportunities', unit: 'count' },
    ],
    antiPatterns: ['Founder owns every important sales conversation', 'Delivery leaders hear about demand only after the deal is sold'],
    recommendedActions: ['Make pipeline visible to delivery leaders', 'Assign account growth ownership', 'Invite delivery expertise into key pursuits early'],
    coachingUse: 'Use for founder bottleneck, team selling, and client expansion coaching.',
    promptUse: 'Inject when userMessage includes team selling, founder-led sales, account growth, or pipeline visibility.',
    confidence: 'high',
    sourceNotes: ['Pairs with $50M founder bottleneck cards.'],
  }),
  card({
    id: 'pwm-growth-l3-repeatable-growth',
    domains: ['growth', 'commercial', 'operations'],
    topics: ['l3', 'repeatable_growth', 'positioning', 'icp', 'pipeline_discipline', 'sales_process'],
    appliesWhen: ['growth is inconsistent', 'pipeline quality issue', 'positioning unclear', 'repeatable sales process needed'],
    principle: 'L3 makes growth repeatable through clear ICP, positioning, pipeline discipline, and sales process consistency.',
    evidenceSummary: 'Repeatable growth means the firm can explain what it sells, to whom, why now, and how opportunities progress.',
    metrics: [
      { name: 'icp_defined', unit: 'boolean' },
      { name: 'positioning_statement_defined', unit: 'boolean' },
      { name: 'pipeline_stage_hygiene', unit: 'qualitative' },
    ],
    antiPatterns: ['Confusing a busy pipeline with a quality pipeline', 'Letting every practice describe the firm differently'],
    recommendedActions: ['Check ICP and positioning before scaling sales activity', 'Clean pipeline stages', 'Review stuck opportunities by owner'],
    coachingUse: 'Use for inconsistent growth and weak pipeline discipline.',
    promptUse: 'Inject when growth maturity target is repeatable growth or pipeline quality is weak.',
    confidence: 'high',
    sourceNotes: ['Method card for repeatable commercial motion.'],
  }),
  card({
    id: 'pwm-growth-l4-revenue-efficiency',
    domains: ['growth', 'finance', 'leadership'],
    topics: ['l4', 'revenue_efficiency', 'book_to_bill', 'revenue_per_consultant', 'forecast_accuracy', 'margin_aware_growth'],
    appliesWhen: ['growth with margin pressure', 'revenue efficiency question', 'book-to-bill issue', 'forecast confidence'],
    principle: 'L4 optimizes revenue efficiency so growth converts into margin, confidence, and scalable delivery rather than uncontrolled hiring.',
    evidenceSummary: 'Revenue efficiency connects pipeline, win rate, pricing, utilisation, margin, and capacity into one commercial operating picture.',
    metrics: [
      { name: 'book_to_bill', unit: 'ratio' },
      { name: 'revenue_per_billable_consultant', unit: 'currency' },
      { name: 'forecast_accuracy', unit: 'percent' },
    ],
    antiPatterns: ['Growing revenue while margin and delivery confidence decline', 'Hiring ahead of validated demand without visibility'],
    recommendedActions: ['Review book-to-bill with utilisation and margin', 'Check revenue per billable consultant', 'Use forecast confidence to pace hiring'],
    coachingUse: 'Use for executive growth efficiency and margin-aware scaling questions.',
    promptUse: 'Inject when userMessage includes revenue efficiency, book-to-bill, forecast, or margin-aware growth.',
    confidence: 'high',
    sourceNotes: ['Connects growth and operations tracks without duplicating raw source text.'],
  }),
  card({
    id: 'pwm-growth-icp-positioning-prerequisites',
    domains: ['growth', 'commercial_strategy'],
    topics: ['icp', 'positioning', 'right_fit_work', 'market_focus', 'qualification'],
    appliesWhen: ['pipeline quality low', 'win rate weak', 'firm chasing too many segments', 'positioning not defined'],
    principle: 'ICP and positioning come before scale; otherwise more sales activity creates more noise and lower-quality work.',
    evidenceSummary: 'The growth method treats right-fit focus as a prerequisite for repeatable pipeline and better delivery-market fit.',
    metrics: [
      { name: 'icp_defined', unit: 'boolean' },
      { name: 'positioning_statement_defined', unit: 'boolean' },
      { name: 'qualified_pipeline_ratio', unit: 'percent' },
    ],
    antiPatterns: ['Accepting every opportunity as pipeline', 'Trying to improve win rate without narrowing fit'],
    recommendedActions: ['Name the ICP gap', 'Separate qualified pipeline from total pipeline', 'Coach the user toward market focus before volume'],
    coachingUse: 'Use for strategic commercial coaching before recommending activity increases.',
    promptUse: 'Inject when user asks about pipeline quality, positioning, ICP, or right-fit clients.',
    confidence: 'high',
    sourceNotes: ['Product-safe summary of commercial prerequisites.'],
  }),
  card({
    id: 'pwm-growth-pipeline-discipline',
    domains: ['growth', 'commercial', 'operations'],
    topics: ['pipeline', 'pipeline_discipline', 'pipeline_gap', 'revenue_confidence', 'forecast', 'forward_booking'],
    appliesWhen: ['pipeline gap', 'revenue confidence at risk', 'forecast uncertainty', 'forward booking gap tied to demand'],
    principle: 'Pipeline discipline is the bridge between future revenue and future resourcing; weak pipeline visibility becomes delivery uncertainty.',
    evidenceSummary: 'Commercial cadence should show what is real, what is at risk, and what demand means for staffing before the delivery team feels it.',
    metrics: [
      { name: 'pipeline_coverage', unit: 'multiple' },
      { name: 'revenue_confidence', unit: 'qualitative' },
      { name: 'forward_booking_weeks', unit: 'weeks' },
    ],
    antiPatterns: ['Treating pipeline as a sales-only list', 'Ignoring delivery capacity when pipeline shifts'],
    recommendedActions: ['Review pipeline quality and stage age', 'Connect near-term pipeline to booking gaps', 'Escalate revenue confidence changes to resourcing cadence'],
    coachingUse: 'Use for pipeline gaps, forward booking risk, and revenue confidence coaching.',
    promptUse: 'Inject when insight.metric is forwardBookingWeeks or userMessage mentions pipeline gap, forecast, or revenue confidence.',
    confidence: 'high',
    sourceNotes: ['Designed for selector coverage of pipeline and booking gaps.'],
  }),
  card({
    id: 'pwm-growth-team-selling',
    domains: ['growth', 'sales', 'leadership', 'client_relationships'],
    topics: ['team_selling', 'account_growth', 'client_relationships', 'delivery_led_growth', 'founder_bottleneck'],
    appliesWhen: ['sales owner concentration', 'client expansion opportunity', 'founder bottleneck', 'delivery leaders not selling'],
    principle: 'Team selling increases trust and scale by turning client relationships into a shared operating asset.',
    evidenceSummary: 'When delivery leaders and account owners share growth responsibility, the firm can farm existing clients without making every sale founder-dependent.',
    metrics: [
      { name: 'account_expansion_opportunities', unit: 'count' },
      { name: 'multi_person_relationship_coverage', unit: 'percent' },
    ],
    antiPatterns: ['One person owns all strategic relationships', 'Delivery value never turns into expansion conversations'],
    recommendedActions: ['Identify accounts with single-threaded relationships', 'Prepare account expansion plays', 'Invite delivery leaders into client growth reviews'],
    coachingUse: 'Use for client growth and founder-dependency coaching.',
    promptUse: 'Inject when userMessage includes team selling, account growth, client expansion, or founder bottleneck.',
    confidence: 'high',
    sourceNotes: ['Complements $50M farming and QBR principles.'],
  }),
  card({
    id: 'pwm-growth-revenue-efficiency',
    domains: ['growth', 'finance', 'operations'],
    topics: ['revenue_efficiency', 'margin_aware_growth', 'utilisation', 'utilization', 'pricing', 'book_to_bill'],
    appliesWhen: ['growth with delivery strain', 'utilisation and pipeline both matter', 'book-to-bill review', 'pricing leverage question'],
    principle: 'Efficient growth improves revenue quality, not just revenue volume.',
    evidenceSummary: 'Revenue efficiency improves when sales focus, pricing, delivery leverage, and utilisation reinforce each other.',
    metrics: [
      { name: 'book_to_bill', unit: 'ratio' },
      { name: 'utilisation', unit: 'percent' },
      { name: 'project_margin', unit: 'percent' },
    ],
    antiPatterns: ['Winning low-margin work to solve a short-term pipeline gap', 'Solving utilisation by filling people with poor-fit delivery'],
    recommendedActions: ['Check margin before recommending more sales volume', 'Pair pipeline review with utilisation and project margin', 'Prioritize right-fit demand'],
    coachingUse: 'Use when growth and operations signals need to be reconciled.',
    promptUse: 'Inject for combined pipeline, utilisation, pricing, and margin questions.',
    confidence: 'high',
    sourceNotes: ['Keeps growth recommendations aligned with services economics.'],
  }),
]);

module.exports = {
  source: {
    ...SOURCE,
    cards,
  },
};
