'use strict';

const SOURCE = Object.freeze({
  id: 'spi_benchmark_2025',
  title: 'SPI Benchmark 2025',
  type: 'benchmark',
  authority: 'external',
  version: '2025',
  requiresModel: false,
  requiresApi: false,
});

function card(input) {
  return {
    sourceId: SOURCE.id,
    sourceTitle: SOURCE.title,
    sourceType: SOURCE.type,
    authority: SOURCE.authority,
    version: SOURCE.version,
    ...input,
  };
}

const cards = Object.freeze([
  card({
    id: 'spi-service-performance-pillars',
    domains: ['benchmark', 'operations', 'leadership', 'client_relationships', 'talent', 'service_execution', 'finance'],
    topics: ['maturity', 'pillars', 'balanced_scorecard', 'professional_services_maturity'],
    appliesWhen: ['general firm health assessment', 'cross-functional operating review', 'board or leadership summary'],
    principle: 'Assess service performance across leadership, client relationships, talent, service execution, and finance rather than optimizing one metric in isolation.',
    evidenceSummary: 'The SPI maturity model frames performance through five connected pillars; durable improvement comes from raising the operating system, not chasing a single dashboard number.',
    metrics: [
      { name: 'maturity_level', unit: 'level', notes: 'Use as a directional operating benchmark.' },
      { name: 'pillar_balance', unit: 'qualitative', notes: 'Look for one pillar constraining the others.' },
    ],
    antiPatterns: ['Treating utilisation as the only operating metric', 'Separating finance, delivery, and talent decisions into disconnected reviews'],
    recommendedActions: ['Score the firm against all five pillars', 'Identify the weakest pillar before prescribing actions', 'Tie each insight to the pillar it improves'],
    coachingUse: 'Use this when the user asks broadly how the firm is tracking or what to focus on next.',
    promptUse: 'Inject as high-level framing for multi-domain operating questions and maturity summaries.',
    confidence: 'high',
    sourceNotes: ['Product-safe synthesis; no raw benchmark text embedded.'],
  }),
  card({
    id: 'spi-maturity-levels',
    domains: ['benchmark', 'leadership', 'operations'],
    topics: ['maturity', 'maturity_levels', 'level_1', 'level_2', 'level_3', 'level_4', 'level_5'],
    appliesWhen: ['maturity assessment', 'operating model comparison', 'leadership asks where to level up'],
    principle: 'Use maturity levels to explain why firms with similar headcount can produce different predictability, margin, and growth outcomes.',
    evidenceSummary: 'Higher maturity firms tend to run more repeatable processes, tighter execution loops, and better cross-functional governance.',
    metrics: [
      { name: 'maturity_level', unit: 'level' },
      { name: 'process_repeatability', unit: 'qualitative' },
    ],
    antiPatterns: ['Calling every issue a one-off problem', 'Skipping process maturity and only asking for more reports'],
    recommendedActions: ['Name the current maturity constraint', 'Translate the next level into one operating habit', 'Avoid overwhelming the user with all levels at once'],
    coachingUse: 'Use maturity language to turn scattered symptoms into a clear next operating step.',
    promptUse: 'Inject when tenantSnapshot.maturity or user language references maturity, maturity level, or operating discipline.',
    confidence: 'high',
    sourceNotes: ['Summarized maturity concept for assistant coaching.'],
  }),
  card({
    id: 'spi-utilization-benchmark-threshold',
    domains: ['benchmark', 'talent', 'service_execution', 'operations'],
    topics: ['utilisation', 'utilization', 'billable_utilisation', 'capacity', 'benchmark_gap', 'threshold'],
    appliesWhen: ['utilisation below target', 'low utilisation staff', 'capacity gap', 'bench time'],
    principle: 'A utilisation gap is a commercial and resourcing signal, not just a timesheet statistic.',
    evidenceSummary: 'Top-performing service firms typically manage billable utilisation against explicit thresholds; small percentage-point movement has meaningful annual revenue impact.',
    metrics: [
      { name: 'billable_utilisation', target: '68-70', unit: 'percent', notes: 'Use exact target from tenant benchmark context when available.' },
      { name: 'revenue_per_utilisation_point', unit: 'currency', notes: 'Calculate from billable headcount, charge-out rate, and annual hours.' },
    ],
    antiPatterns: ['Blaming individuals before checking demand, allocation, and booking gaps', 'Using worked hours without capacity context'],
    recommendedActions: ['Break utilisation down by person and upcoming bookings', 'Connect low utilisation to pipeline and staffing decisions', 'Quantify the one-point opportunity'],
    coachingUse: 'Use for utilisation insights, low-util staff coaching, and capacity planning conversations.',
    promptUse: 'Inject when insight.metric is utilisationRate or userMessage includes utilisation, utilization, capacity, bench, or billable.',
    confidence: 'high',
    sourceNotes: ['Benchmark threshold should be overridden by tenant-specific benchmark targets when present.'],
  }),
  card({
    id: 'spi-project-overrun-on-time-delivery',
    domains: ['benchmark', 'service_execution', 'delivery', 'project_control'],
    topics: ['project_overrun', 'on_time_delivery', 'budget_burn', 'delivery_margin', 'project_health'],
    appliesWhen: ['project over budget', 'burn rate problem', 'delivery margin risk', 'on-time delivery risk'],
    principle: 'Project overrun and on-time delivery are leading indicators of delivery discipline and future margin pressure.',
    evidenceSummary: 'Mature firms monitor overruns early enough to change scope, staffing, commercial terms, or client expectations before margin is lost.',
    metrics: [
      { name: 'project_overrun', unit: 'percent' },
      { name: 'on_time_delivery', unit: 'percent' },
      { name: 'project_margin', unit: 'percent' },
    ],
    antiPatterns: ['Reviewing project margin only after invoice closeout', 'Mixing budget, worked, and invoiced facts at detail grain'],
    recommendedActions: ['Surface projects over budget by named project', 'Separate scope issue from staffing issue', 'Prompt a PM conversation when burn exceeds plan'],
    coachingUse: 'Use for budget vs actual, project health, and project margin risk insights.',
    promptUse: 'Inject when insight mentions over budget, burn, project health, delivery margin, or on-time delivery.',
    confidence: 'high',
    sourceNotes: ['Keeps benchmark framing separate from raw reporting SQL rules.'],
  }),
  card({
    id: 'spi-revenue-per-billable-consultant',
    domains: ['benchmark', 'finance', 'talent', 'growth'],
    topics: ['revenue_per_billable_consultant', 'revenue_efficiency', 'billable_headcount', 'utilisation', 'utilization'],
    appliesWhen: ['leadership asks about productivity', 'growth without hiring', 'utilisation opportunity sizing'],
    principle: 'Revenue per billable consultant ties pricing, utilisation, delivery leverage, and staffing mix into one executive productivity signal.',
    evidenceSummary: 'Benchmark comparisons can show whether growth is coming from better leverage and pricing or simply from adding more people.',
    metrics: [
      { name: 'revenue_per_billable_consultant', unit: 'currency' },
      { name: 'billable_headcount', unit: 'people' },
      { name: 'average_charge_rate', unit: 'currency_per_hour' },
    ],
    antiPatterns: ['Celebrating revenue growth while productivity per consultant falls', 'Comparing teams without normalizing by billable headcount'],
    recommendedActions: ['Calculate revenue per billable consultant', 'Compare trend to utilisation and margin', 'Use it to frame staffing and pricing decisions'],
    coachingUse: 'Use when users ask how to grow without simply hiring more consultants.',
    promptUse: 'Inject for revenue efficiency, headcount leverage, and executive growth questions.',
    confidence: 'high',
    sourceNotes: ['Metric definition must use tenant reporting facts when wired later.'],
  }),
  card({
    id: 'spi-profitability-ebitda',
    domains: ['benchmark', 'finance', 'operations', 'leadership'],
    topics: ['profitability', 'ebitda', 'firm_margin', 'services_margin', 'operating_margin'],
    appliesWhen: ['firm margin question', 'profitability review', 'finance operating review', 'leadership asks about margin'],
    principle: 'EBITDA and operating margin are lagging outcomes of utilisation, project control, pricing, and operating discipline.',
    evidenceSummary: 'Profitability benchmark gaps should be decomposed into delivery margin, labour leverage, pricing, utilisation, and overhead rather than treated as one finance-only issue.',
    metrics: [
      { name: 'ebitda', unit: 'percent' },
      { name: 'services_margin', unit: 'percent' },
      { name: 'project_margin', unit: 'percent' },
    ],
    antiPatterns: ['Treating EBITDA as an accounting-only metric', 'Ignoring WIP and overruns when explaining margin'],
    recommendedActions: ['Decompose margin into delivery and firm-level levers', 'Name the operational driver behind the finance metric', 'Connect margin review to a cadence'],
    coachingUse: 'Use for profitability, EBITDA, and margin coaching.',
    promptUse: 'Inject when userMessage includes EBITDA, profit, margin, services margin, or firm margin.',
    confidence: 'high',
    sourceNotes: ['Financial metric definitions must remain tenant-specific.'],
  }),
  card({
    id: 'spi-talent-and-utilization',
    domains: ['benchmark', 'talent', 'service_execution', 'operations'],
    topics: ['talent', 'utilisation', 'utilization', 'capacity', 'attrition', 'team_health', 'resource_planning'],
    appliesWhen: ['low utilisation staff', 'overloaded team', 'capacity planning', 'resourcing tradeoff'],
    principle: 'Talent performance must balance utilisation, workload sustainability, capability fit, and retention risk.',
    evidenceSummary: 'High maturity firms manage utilisation alongside talent health; persistent underuse or overload both signal an operating issue.',
    metrics: [
      { name: 'billable_utilisation', unit: 'percent' },
      { name: 'attrition', unit: 'percent' },
      { name: 'capacity_gap', unit: 'hours' },
    ],
    antiPatterns: ['Using utilisation as a blunt performance ranking', 'Ignoring leave, capacity, or sales demand when coaching individuals'],
    recommendedActions: ['Check the booking gap before coaching performance', 'Separate market demand from individual availability', 'Escalate sustained overload as a retention signal'],
    coachingUse: 'Use for people-sensitive utilisation and capacity messages.',
    promptUse: 'Inject when insight includes lowUtilisationStaff, capacityGaps, or people utilisation.',
    confidence: 'high',
    sourceNotes: ['Avoids naming individual performance as fault without supporting tenant facts.'],
  }),
  card({
    id: 'spi-maturity-improvement-performance-lever',
    domains: ['benchmark', 'leadership', 'operations', 'growth', 'finance'],
    topics: ['maturity_improvement', 'performance_lever', 'operating_system', 'decision_cadence'],
    appliesWhen: ['multiple recurring issues', 'leadership wants next best move', 'maturity gap spans finance delivery and sales'],
    principle: 'The practical lever is not more dashboards; it is a higher-quality operating loop that makes better decisions earlier.',
    evidenceSummary: 'Maturity improvements show up through repeatable decisions, clearer ownership, and fewer surprises across revenue, delivery, talent, and finance.',
    metrics: [
      { name: 'maturity_level', unit: 'level' },
      { name: 'decision_cadence_adherence', unit: 'qualitative' },
    ],
    antiPatterns: ['Creating reports with no decision owner', 'Letting every function run its own disconnected cadence'],
    recommendedActions: ['Tie each insight to a named decision', 'Create a weekly or monthly cadence around the constraint', 'Measure whether the operating habit changed'],
    coachingUse: 'Use to push from insight to action without making the product feel like a passive dashboard.',
    promptUse: 'Inject when the assistant needs to coach a next operating habit from a benchmark gap.',
    confidence: 'high',
    sourceNotes: ['Product-safe summary of SPI maturity improvement logic.'],
  }),
]);

module.exports = {
  source: {
    ...SOURCE,
    cards,
  },
};
