'use strict';

const operationsTrack = [
  {
    id: 'ops_l0',
    track: 'operations',
    level: 0,
    name: 'Switch',
    goal: 'Get data into Projectworks and go live with confidence',
    outcome: 'Firm is live on Projectworks with core data imported and team onboarded.',
    indicators: [],
    habits: { daily: [], weekly: [], monthly: [] },
    benchmarks: [],
  },
  {
    id: 'ops_l1',
    track: 'operations',
    level: 1,
    name: 'Lean Admin',
    goal: 'Automate the basics',
    outcome: 'Admin overhead drops; timesheets flow into invoices without manual intervention.',
    indicators: [
      {
        id: 'timesheetCompletionRate',
        name: 'Timesheet Completion Rate',
        description: 'Every team member completes timesheet before end of day',
        threshold: 0.8,
        unit: 'percent',
        cadence: 'daily',
        priority: 'H',
        dataField: 'timesheetCompletionRate',
      },
      {
        id: 'invoicesGeneratedFromTimesheets',
        name: 'Invoices Generated From Timesheets',
        description: 'Invoices generated from approved timesheets',
        threshold: true,
        unit: 'boolean',
        cadence: 'weekly',
        priority: 'H',
        dataField: 'invoicesGeneratedFromTimesheets',
      },
      {
        id: 'weeklyTimesheetReview',
        name: 'Weekly Timesheet Review',
        description: 'Timesheet review by person responsible for ops',
        threshold: true,
        unit: 'boolean',
        cadence: 'weekly',
        priority: 'H',
        dataField: 'weeklyTimesheetReview',
      },
    ],
    habits: {
      daily: [
        'Every team member completes timesheet entry before end of working day',
      ],
      weekly: [
        'Timesheet review by ops lead',
        "Automated nudge to anyone who hasn't completed timesheets",
        'Approve invoices generated from approved timesheets',
      ],
      monthly: [],
    },
    benchmarks: [],
  },
  {
    id: 'ops_l2',
    track: 'operations',
    level: 2,
    name: 'Visibility',
    goal: 'Deliver consistently at scale',
    outcome: 'Resourcing is proactive; utilisation is tracked and improving.',
    indicators: [
      {
        id: 'forwardBookingWeeks',
        name: 'Forward Booking Weeks',
        description: 'Resources booked 8+ weeks ahead',
        threshold: 8,
        unit: 'weeks',
        cadence: 'weekly',
        priority: 'H',
        dataField: 'forwardBookingWeeks',
      },
      {
        id: 'utilisationRate',
        name: 'Utilisation Rate',
        description: 'Billable utilisation tracked and above 68%',
        threshold: 0.68,
        unit: 'percent',
        cadence: 'monthly',
        priority: 'H',
        dataField: 'utilisationRate',
      },
      {
        id: 'weeklyResourceMeeting',
        name: 'Weekly Resource Meeting',
        description: 'Weekly resource planning meeting running',
        threshold: true,
        unit: 'boolean',
        cadence: 'weekly',
        priority: 'H',
        dataField: 'weeklyResourceMeeting',
      },
      {
        id: 'dealReviewMeeting',
        name: 'Deal Review Meeting',
        description: 'Deal review meeting connecting pipeline to resourcing',
        threshold: true,
        unit: 'boolean',
        cadence: 'weekly',
        priority: '!',
        dataField: 'dealReviewMeeting',
      },
    ],
    habits: {
      daily: ['All L1 daily habits maintained'],
      weekly: [
        'Weekly resource planning meeting — reviewing capacity, allocations, forward resourcing',
        'Deal Review Meeting — connect pipeline to resourcing',
      ],
      monthly: [],
    },
    benchmarks: [
      {
        metric: 'billableUtilisation',
        spi2025: 68.9,
        pwAnzAvg: 67.1,
        pwTop50: 69.8,
        unit: 'percent',
        dollarImpact: '1pp improvement in utilisation = ~$113k/yr on a 37-person billable team at $153/hr implied charge-out',
      },
      {
        metric: 'revenuePerBillable',
        spi2025: 199000,
        pwAnzAvg: 205000,
        pwTop50: 222000,
        unit: 'dollars',
        dollarImpact: 'Top 50% firms generate $629k more revenue/yr on same headcount vs PW ANZ average',
      },
    ],
  },
  {
    id: 'ops_l3',
    track: 'operations',
    level: 3,
    name: 'Delivery Margins',
    goal: 'Understand and control project profitability',
    outcome: 'Every project has a visible margin; at-risk projects surface before they blow out.',
    indicators: [
      {
        id: 'weeklyWIPReview',
        name: 'Weekly WIP Review',
        description: 'Weekly WIP review examining margin, burn, cost at complete',
        threshold: true,
        unit: 'boolean',
        cadence: 'weekly',
        priority: 'H',
        dataField: 'weeklyWIPReview',
      },
      {
        id: 'projectMarginTracked',
        name: 'Project Margin Tracked',
        description: 'Project margin visible per project',
        threshold: true,
        unit: 'boolean',
        cadence: 'monthly',
        priority: 'H',
        dataField: 'projectMarginTracked',
      },
      {
        id: 'burnRateMonitored',
        name: 'Burn Rate Monitored',
        description: 'At-risk project signals visible in real time',
        threshold: true,
        unit: 'boolean',
        cadence: 'weekly',
        priority: 'H',
        dataField: 'burnRateMonitored',
      },
    ],
    habits: {
      daily: [
        'All L1 and L2 daily habits maintained',
        'At-risk project signals visible in real-time',
      ],
      weekly: [
        'Weekly project WIP review — margin, burn, cost at complete, projects at risk',
        'Must be a decision forum not a status report',
      ],
      monthly: [],
    },
    benchmarks: [
      {
        metric: 'projectMargin',
        spi2025: 35.9,
        pwAnzAvg: null,
        pwTop50: null,
        unit: 'percent',
      },
      {
        metric: 'servicesMargin',
        spi2025: null,
        pwAnzAvg: 10.3,
        pwTop50: 12.5,
        unit: 'percent',
        dollarImpact: 'High-adoption uplift: +50% on services margin',
      },
    ],
  },
  {
    id: 'ops_l4',
    track: 'operations',
    level: 4,
    name: 'Firm Margins',
    goal: 'Scale a profitable consulting business',
    outcome: 'Firm-level profitability is tracked, forecast, and improving quarter on quarter.',
    indicators: [
      {
        id: 'forecastingEnabled',
        name: 'Forecasting Enabled',
        description: 'Revenue forecasting active',
        threshold: true,
        unit: 'boolean',
        cadence: 'monthly',
        priority: 'H',
        dataField: 'forecastingEnabled',
      },
      {
        id: 'firmMarginReporting',
        name: 'Firm Margin Reporting',
        description: 'Firm-level operating margin being tracked',
        threshold: true,
        unit: 'boolean',
        cadence: 'monthly',
        priority: 'H',
        dataField: 'firmMarginReporting',
      },
    ],
    habits: {
      daily: ['All prior daily habits maintained — data flows automatically'],
      weekly: [
        'WIP and resource planning meetings continue from L3',
        'No new weekly ritual at L4 — rhythm maintained',
      ],
      monthly: [
        'Firm-level margin review',
        'Forecast vs actual review',
      ],
    },
    benchmarks: [
      {
        metric: 'ebitda',
        spi2025: 9.8,
        pwAnzAvg: null,
        pwTop50: null,
        unit: 'percent',
      },
      {
        metric: 'yoyRevGrowth',
        spi2025: 4.6,
        pwAnzAvg: 20.5,
        pwTop50: 29.5,
        unit: 'percent',
        dollarImpact: 'High-adoption uplift vs PW ANZ avg: ~+100% YoY revenue growth',
      },
    ],
  },
];

const growthTrack = [
  {
    id: 'growth_l0',
    track: 'growth',
    level: 0,
    name: 'Switch',
    goal: 'Get data into Projectworks and go live with confidence',
    outcome: 'Firm is live on Projectworks with core data imported and team onboarded.',
    indicators: [],
    habits: { daily: [], weekly: [], monthly: [] },
    benchmarks: [],
  },
  {
    id: 'growth_l1',
    track: 'growth',
    level: 1,
    name: 'Win More Work',
    goal: 'Get good at selling',
    outcome: 'Baseline sales metrics established; pipeline is visible for the first time.',
    indicators: [
      {
        id: 'proposalVolumeTracked',
        name: 'Proposal Volume Tracked',
        description: 'Proposal volume being tracked',
        threshold: true,
        unit: 'boolean',
        cadence: 'monthly',
        priority: '!',
        dataField: 'proposalVolumeTracked',
      },
      {
        id: 'winRateTracked',
        name: 'Win Rate Tracked',
        description: 'Win rate tracked for first time — baseline established',
        threshold: true,
        unit: 'boolean',
        cadence: 'monthly',
        priority: '!',
        dataField: 'winRateTracked',
      },
      {
        id: 'icpDefined',
        name: 'ICP Defined',
        description: 'Ideal Customer Profile documented and shared',
        threshold: true,
        unit: 'boolean',
        cadence: 'monthly',
        priority: 'H',
        dataField: 'icpDefined',
      },
    ],
    habits: {
      daily: [],
      weekly: ['Pipeline review — proposals out, follow-ups due'],
      monthly: ['Win/loss review — what won, what lost, why'],
    },
    benchmarks: [
      {
        metric: 'winRate',
        spi2025: 48.1,
        pwAnzAvg: null,
        pwTop50: null,
        unit: 'percent',
      },
      {
        metric: 'serviceDiscount',
        spi2025: 8.1,
        pwAnzAvg: null,
        pwTop50: null,
        unit: 'percent',
      },
    ],
  },
  {
    id: 'growth_l2',
    track: 'growth',
    level: 2,
    name: 'Team Selling',
    goal: 'Improve ability to win work consistently',
    outcome: 'Sales is a team sport; pipeline is owned and maintained across the firm.',
    indicators: [
      {
        id: 'pipelineVisibleToTeam',
        name: 'Pipeline Visible To Team',
        description: 'Pipeline visible and maintained by whole team',
        threshold: true,
        unit: 'boolean',
        cadence: 'weekly',
        priority: 'H',
        dataField: 'pipelineVisibleToTeam',
      },
      {
        id: 'positioningStatementDefined',
        name: 'Positioning Statement Defined',
        description: 'Positioning statement built and embedded in sales materials',
        threshold: true,
        unit: 'boolean',
        cadence: 'monthly',
        priority: 'H',
        dataField: 'positioningStatementDefined',
      },
      {
        id: 'existingClientGrowthTracked',
        name: 'Existing Client Growth Tracked',
        description: 'Existing client growth being tracked alongside new logos',
        threshold: true,
        unit: 'boolean',
        cadence: 'monthly',
        priority: '!',
        dataField: 'existingClientGrowthTracked',
      },
    ],
    habits: {
      daily: [],
      weekly: [
        'Team pipeline review — not just founder-owned',
        'Existing client health check',
      ],
      monthly: ['Positioning language audit — is the team selling consistently?'],
    },
    benchmarks: [
      {
        metric: 'pipelineVsQtrForecast',
        spi2025: 154,
        pwAnzAvg: null,
        pwTop50: null,
        unit: 'percent',
      },
      {
        metric: 'backlogVsQtrTarget',
        spi2025: 43.8,
        pwAnzAvg: null,
        pwTop50: null,
        unit: 'percent',
      },
    ],
  },
  {
    id: 'growth_l3',
    track: 'growth',
    level: 3,
    name: 'Repeatable Growth',
    goal: 'Understand and control growth economics',
    outcome: 'Growth is systematic; conversion rates and forecast accuracy are improving.',
    indicators: [
      {
        id: 'cagrTracked',
        name: 'CAGR Tracked',
        description: 'CAGR tracked as meaningful 3-year trend',
        threshold: true,
        unit: 'boolean',
        cadence: 'quarterly',
        priority: 'H',
        dataField: 'cagrTracked',
      },
      {
        id: 'forecastAccuracy',
        name: 'Forecast Accuracy',
        description: 'Revenue forecast accuracy above 88%',
        threshold: 0.88,
        unit: 'percent',
        cadence: 'monthly',
        priority: 'H',
        dataField: 'forecastAccuracy',
      },
      {
        id: 'conversionRatesKnown',
        name: 'Conversion Rates Known',
        description: 'Conversion rates known at every pipeline stage',
        threshold: true,
        unit: 'boolean',
        cadence: 'monthly',
        priority: 'H',
        dataField: 'conversionRatesKnown',
      },
    ],
    habits: {
      daily: [],
      weekly: ['Pipeline stage conversion review'],
      monthly: [
        'CAGR and forecast accuracy review',
        'Pipeline diagnosis — where are weak points?',
      ],
    },
    benchmarks: [
      {
        metric: 'yoyRevGrowth',
        spi2025: 4.6,
        pwAnzAvg: 20.5,
        pwTop50: 29.5,
        unit: 'percent',
      },
      {
        metric: 'forecastAccuracy',
        spi2025: 87.9,
        pwAnzAvg: null,
        pwTop50: null,
        unit: 'percent',
      },
      {
        metric: 'salesCycleDays',
        spi2025: 88,
        pwAnzAvg: null,
        pwTop50: null,
        unit: 'count',
      },
    ],
  },
  {
    id: 'growth_l4',
    track: 'growth',
    level: 4,
    name: 'Revenue Efficiency',
    goal: 'Scale a profitable consulting business',
    outcome: 'Growth investment is allocated by return; sales and delivery are fully connected.',
    indicators: [
      {
        id: 'ltvCacKnown',
        name: 'LTV/CAC Known',
        description: 'LTV/CAC economics understood per client segment',
        threshold: true,
        unit: 'boolean',
        cadence: 'quarterly',
        priority: 'H',
        dataField: 'ltvCacKnown',
      },
      {
        id: 'growthInvestmentByReturn',
        name: 'Growth Investment By Return',
        description: 'Growth investment allocated by demonstrated return',
        threshold: true,
        unit: 'boolean',
        cadence: 'quarterly',
        priority: 'H',
        dataField: 'growthInvestmentByReturn',
      },
      {
        id: 'salesDeliveryConnected',
        name: 'Sales and Delivery Connected',
        description: 'Sales and delivery fully connected — winning work firm can profitably deliver',
        threshold: true,
        unit: 'boolean',
        cadence: 'monthly',
        priority: 'H',
        dataField: 'salesDeliveryConnected',
      },
    ],
    habits: {
      daily: [],
      weekly: [],
      monthly: [
        'LTV/CAC review by client segment',
        'Growth investment allocation review',
        'Cross-track tension check: Ops L3 must keep pace with Growth L4',
      ],
    },
    benchmarks: [
      {
        metric: 'salesQuotaPerPerson',
        spi2025: 1430000,
        pwAnzAvg: null,
        pwTop50: null,
        unit: 'dollars',
      },
      {
        metric: 'salesCostsPct',
        spi2025: 4.8,
        pwAnzAvg: null,
        pwTop50: null,
        unit: 'percent',
      },
      {
        metric: 'marketingCostsPct',
        spi2025: 2.5,
        pwAnzAvg: null,
        pwTop50: null,
        unit: 'percent',
      },
    ],
  },
];

module.exports = { operationsTrack, growthTrack };
