'use strict';

const ACTION_REGISTRY_VERSION = 'action-registry.v1';

const ACTION_DEFINITIONS = Object.freeze([
  {
    id: 'create_project',
    label: 'Create project',
    description: 'Create a new Projectworks project after required details are confirmed.',
    category: 'project',
    requiredInputs: ['name', 'client', 'billingMethod', 'projectManager'],
    optionalInputs: ['startDate', 'endDate', 'currency', 'status', 'budget'],
    capabilityRequired: { system: 'projectworks', area: 'actions', key: 'createProject' },
    riskLevel: 'medium',
    requiresConfirmation: true,
    financial: false,
    destructive: false,
    enabledByDefault: false,
  },
  {
    id: 'update_project',
    label: 'Update project',
    description: 'Update project metadata such as dates, status, PM, or budget fields.',
    category: 'project',
    requiredInputs: ['projectId'],
    optionalInputs: ['status', 'contractualStatus', 'projectManager', 'startDate', 'endDate', 'budget'],
    capabilityRequired: { system: 'projectworks', area: 'actions', key: 'updateProject' },
    riskLevel: 'high',
    requiresConfirmation: true,
    financial: false,
    destructive: true,
    enabledByDefault: false,
  },
  {
    id: 'create_budget_line',
    label: 'Create budget line',
    description: 'Create a budget line on a Projectworks project.',
    category: 'financial',
    requiredInputs: ['projectId', 'name', 'amount'],
    optionalInputs: ['type', 'glCode', 'currency'],
    capabilityRequired: { system: 'projectworks', area: 'actions', key: 'createBudgetLine' },
    riskLevel: 'high',
    requiresConfirmation: true,
    financial: true,
    destructive: false,
    enabledByDefault: false,
  },
  {
    id: 'update_budget',
    label: 'Update budget',
    description: 'Update an existing project budget amount or budget line.',
    category: 'financial',
    requiredInputs: ['projectId', 'budgetId', 'amount'],
    optionalInputs: ['name', 'type', 'glCode', 'currency'],
    capabilityRequired: { system: 'projectworks', area: 'actions', key: 'updateBudget' },
    riskLevel: 'high',
    requiresConfirmation: true,
    financial: true,
    destructive: true,
    enabledByDefault: false,
  },
  {
    id: 'create_timecode',
    label: 'Create timecode',
    description: 'Create a timecode on a Projectworks project.',
    category: 'project_setup',
    requiredInputs: ['projectId', 'name', 'billable'],
    optionalInputs: ['type', 'rate', 'assignedPersonIds'],
    capabilityRequired: { system: 'projectworks', area: 'actions', key: 'createTimecode' },
    riskLevel: 'medium',
    requiresConfirmation: true,
    financial: false,
    destructive: false,
    enabledByDefault: false,
  },
  {
    id: 'create_resource_booking',
    label: 'Create resource booking',
    description: 'Book a person onto a project for a date range and hours.',
    category: 'resourcing',
    requiredInputs: ['projectId', 'personId', 'startDate', 'endDate', 'hours'],
    optionalInputs: ['role', 'notes'],
    capabilityRequired: { system: 'projectworks', area: 'actions', key: 'createResourceBooking' },
    riskLevel: 'medium',
    requiresConfirmation: true,
    financial: false,
    destructive: false,
    enabledByDefault: false,
  },
  {
    id: 'create_draft_invoice',
    label: 'Create draft invoice',
    description: 'Create a draft invoice for a Projectworks project.',
    category: 'financial',
    requiredInputs: ['projectId'],
    optionalInputs: ['invoiceDate', 'lineItems', 'amount', 'currency'],
    capabilityRequired: { system: 'projectworks', area: 'actions', key: 'createDraftInvoice' },
    riskLevel: 'high',
    requiresConfirmation: true,
    financial: true,
    destructive: false,
    enabledByDefault: false,
  },
  {
    id: 'flag_ready_to_invoice',
    label: 'Flag ready to invoice',
    description: 'Mark a project or billing item as ready for invoicing.',
    category: 'financial',
    requiredInputs: ['projectId'],
    optionalInputs: ['budgetId', 'note'],
    capabilityRequired: { system: 'projectworks', area: 'actions', key: 'flagReadyToInvoice' },
    riskLevel: 'high',
    requiresConfirmation: true,
    financial: true,
    destructive: false,
    enabledByDefault: false,
  },
  {
    id: 'create_task',
    label: 'Create task',
    description: 'Create a project task for follow-up work.',
    category: 'task',
    requiredInputs: ['projectId', 'name'],
    optionalInputs: ['assigneeId', 'dueDate', 'description'],
    capabilityRequired: { system: 'projectworks', area: 'actions', key: 'createTask' },
    riskLevel: 'low',
    requiresConfirmation: false,
    financial: false,
    destructive: false,
    enabledByDefault: false,
  },
  {
    id: 'update_task',
    label: 'Update task',
    description: 'Update an existing project task.',
    category: 'task',
    requiredInputs: ['taskId'],
    optionalInputs: ['status', 'assigneeId', 'dueDate', 'description'],
    capabilityRequired: { system: 'projectworks', area: 'actions', key: 'updateTask' },
    riskLevel: 'medium',
    requiresConfirmation: true,
    financial: false,
    destructive: true,
    enabledByDefault: false,
  },
  {
    id: 'send_invoice_reminder',
    label: 'Send invoice reminder',
    description: 'Prepare or send a client reminder for an overdue invoice.',
    category: 'financial',
    requiredInputs: ['invoiceId'],
    optionalInputs: ['invoiceNumber', 'clientId', 'clientName', 'message'],
    capabilityRequired: { system: 'projectworks', area: 'actions', key: 'sendInvoiceReminder' },
    riskLevel: 'high',
    requiresConfirmation: true,
    financial: true,
    destructive: false,
    enabledByDefault: false,
  },
]);

function cloneAction(action) {
  return {
    ...action,
    requiredInputs: [...action.requiredInputs],
    optionalInputs: [...action.optionalInputs],
    capabilityRequired: { ...action.capabilityRequired },
  };
}

function getRegisteredActions() {
  return ACTION_DEFINITIONS.map(cloneAction);
}

function getActionDefinition(actionId) {
  const action = ACTION_DEFINITIONS.find(item => item.id === actionId);
  return action ? cloneAction(action) : null;
}

module.exports = {
  ACTION_REGISTRY_VERSION,
  ACTION_DEFINITIONS,
  getRegisteredActions,
  getActionDefinition,
};
